
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author chiss
 */
public class ColorsFrame extends javax.swing.JFrame {

    /**
     * Creates new form ColorsFrame
     */
    public ColorsFrame() {
        initComponents();
        defaultScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colors = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdRed = new javax.swing.JRadioButton();
        rdBlue = new javax.swing.JRadioButton();
        rdGreen = new javax.swing.JRadioButton();
        rdBlack = new javax.swing.JRadioButton();
        txtSelectedColor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        colors.add(rdRed);
        rdRed.setSelected(true);
        rdRed.setText("Red");
        rdRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdRedActionPerformed(evt);
            }
        });

        colors.add(rdBlue);
        rdBlue.setText("Blue");
        rdBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBlueActionPerformed(evt);
            }
        });

        colors.add(rdGreen);
        rdGreen.setText("Green");
        rdGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdGreenActionPerformed(evt);
            }
        });

        colors.add(rdBlack);
        rdBlack.setText("Black");
        rdBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBlackActionPerformed(evt);
            }
        });

        txtSelectedColor.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdRed)
                    .addComponent(rdBlue)
                    .addComponent(rdGreen)
                    .addComponent(rdBlack))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSelectedColor)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rdRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdBlack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSelectedColor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdRedActionPerformed
        txtSelectedColor.setBackground(Color.RED);
        txtSelectedColor.setForeground(Color.WHITE);
        txtSelectedColor.setText("Red is selected");
    }//GEN-LAST:event_rdRedActionPerformed

    private void rdBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBlueActionPerformed
        txtSelectedColor.setBackground(Color.BLUE);
        txtSelectedColor.setForeground(Color.WHITE);
        txtSelectedColor.setText("Blue is selected");
    }//GEN-LAST:event_rdBlueActionPerformed

    private void rdGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdGreenActionPerformed
        txtSelectedColor.setBackground(Color.GREEN);
        txtSelectedColor.setForeground(Color.WHITE);
        txtSelectedColor.setText("Green is selected");
    }//GEN-LAST:event_rdGreenActionPerformed

    private void rdBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBlackActionPerformed
        txtSelectedColor.setBackground(Color.BLACK);
        txtSelectedColor.setForeground(Color.WHITE);
        txtSelectedColor.setText("Black is selected");
    }//GEN-LAST:event_rdBlackActionPerformed
    
    public void defaultScreen(){
        txtSelectedColor.setBackground(Color.RED);
        txtSelectedColor.setForeground(Color.WHITE);
        txtSelectedColor.setText("Red is selected");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup colors;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdBlack;
    private javax.swing.JRadioButton rdBlue;
    private javax.swing.JRadioButton rdGreen;
    private javax.swing.JRadioButton rdRed;
    private javax.swing.JTextField txtSelectedColor;
    // End of variables declaration//GEN-END:variables
}
